### PR TITLE
Scheduler tests and hourly time format changes

### PR DESCRIPTION
**Pull request by varunp2k**

### CODE REVIEW

**Comment by Amatullah** [comment]
The analytics scheduler tests are failing. Please have a look.

**Comment by varunp2k** [comment]
The scheduler tests will fail because the format of the timestamps changed. I've mentioned these to @rjdp he will make the changes to the test when he has the time.

**Comment by Amatullah** [comment]
@rjdp when will this be done? We need to merge hourly into develop by evening.

**Review by Samyak2 — APPROVED** [review]
LGTM

**Pull request merged**
