### PR TITLE
chore: add Anomaly Tests

### PR DESCRIPTION
**Pull request by Amatullah**

### CODE REVIEW

**Comment by varunp2k** [comment]
Comments for the various test cases will help

**Comment by varunp2k** [comment]
There have been a lot of bugs for anomaly over the time, are you sure you have covered all those cases?

**Comment by Amatullah** [comment]
I've tried covering all the cases that I know of. Also for every function I've added test cases for both daily and hourly.

**Comment by Amatullah** [comment]
For comments, each test case is assigned an id (inside the @pytest.mark.parametrize) which describes what the test case is about.

**Review by varunp2k — APPROVED** [review]

**Comment by varunp2k** [comment]
LGTM

**Pull request merged**
