### PR TITLE
Druid configurable count column

### PR DESCRIPTION
**Pull request by rjdp**
- [x] add "count_column" to KPI model https://github.com/chaos-genius/chaos_genius/pull/985/commits/80fd1d09fbe496a8430788bffbc7fbb11fb70925
- [x] add "Update KPI" query to migration script for upgrade instance https://github.com/chaos-genius/chaos_genius/pull/985/commits/80fd1d09fbe496a8430788bffbc7fbb11fb70925
- [x] read "count_column" from configured value in KPI definition instead of using hardcoded "count" value https://github.com/chaos-genius/chaos_genius/pull/985/commits/a318e318b59d0d3a93e70447476aae2a5a34b141
- [x] add KPI validation to make sure selected count_column is of integer type https://github.com/chaos-genius/chaos_genius/pull/985/commits/40856b2da3908133087839385173e1090fe32773
- [x] Fixes for the failing pytests because of this change https://github.com/chaos-genius/chaos_genius/pull/985/commits/c61ea1eb3047c91b9ecc83596aa385476159d884

### CODE REVIEW

**Comment by manassolanki** [comment]
LGTM, Just one question, the count column should be ideally visible in case of druid (or similar data source in future). How are we planning to do the same?

**Comment by rjdp** [comment]
@manassolanki currently its being used only incase when Druid is the datasource ( in KPI add form as well it comes up only when Druid is chosen) , but we plan to use same field when we handle preaggregation usecases across more DBs/DWs

**Comment by manassolanki** [comment]
> @manassolanki currently its being used only incase when Druid is the datasource ( in KPI add form as well it comes up only when Druid is chosen) , but we plan to use same field when we handle preaggregation usecases across more DBs/DWs

ok, you mean this is hardcode on the frontend side right now.

**Comment by rjdp** [comment]
@manassolanki it was hardcoded on backend https://github.com/chaos-genius/chaos_genius/blob/ee1f68bf44af36b50d0ccb8c0824bbbbb079b07d/chaos_genius/core/anomaly/controller.py#L89

**Review by manassolanki — APPROVED** [review]

**Pull request merged**
